### ISSUE TITLE
script 태그 위치 이동

### ISSUE THREAD

**Issue by selenehyun** [gorgeous30/Shoppingmall#1]
https://github.com/gorgeous30/1week_homework/blob/b97cc9e05185b8673f30401d4f410c728463467a/1week_homework.html#L15-L18

지금은 head 태그 안에 있어요!
볼때 필요한 css 파일 빼고는 다 body 안에 넣어서 빠르게 페이지가 로딩되도록 하는것이 좋습니다 :)

**Comment by gorgeous30** [comment]
이후의 수업예시들에서는 javascript 태그를 head 밑의 meta tag 아래에 넣던데, 로딩을 빠르게 하기 위해서는 무조건 body에 넣는 게 좋나요?

**Comment by selenehyun** [comment]
@gorgeous30 자신이 작성한 스크립트가 어떤 역할과 기능을 하는지, 알고 사용하는것이 중요합니다.

말씀하신대로 head에 넣는게 있고, body에 넣는게 있지만 저는 기본적으로 부트스트랩이나 jquery같은 외부 라이브러리/자산 파일들을 head에, 자신이 직접 작성한 프로그램 코드는 body에 넣는것을 추천드리고 있습니다.
