### ISSUE TITLE
input 태그 수정

### ISSUE THREAD

**Issue by selenehyun** [gorgeous30/Shoppingmall#2]
https://github.com/gorgeous30/1week_homework/blob/b97cc9e05185b8673f30401d4f410c728463467a/1week_homework.html#L60

input 태그는 `<input ~~~ />` 와 같은 모양을 가져야 해요!
지금과 비교해보고 잘 수정해보세요 :)

**Comment by selenehyun** [comment]
https://github.com/gorgeous30/1week_homework/blob/b97cc9e05185b8673f30401d4f410c728463467a/1week_homework.html#L55

이런 부분도 포함해서 전체적으로 한번 점검을 해보시길 바래요!

**Comment by gorgeous30** [comment]
4/13 수정완료
짝꿍이 없는 태그는 끝에 /이 붙어야 할지 안 붙어야 할 지 어떻게 구분하나요
짝꿍이 없는 모든 태그는 끝에 /를 임의적으로 붙여서 써야하는건가요?

**Comment by selenehyun** [comment]
@gorgeous30 네!
만약 정말 잘 모르겠다면 /를 없이 작성한 뒤에, 프리티어를 돌려보세요.
그러면 프리티어가 알아서 붙여줄겁니다 ㅎㅎ

그 결과를 학습해서 앞으로는 프리티어가 없어도 잘 할수 있게 되는것이 중요합니다.
