### ISSUE TITLE
id 수정

### ISSUE THREAD

**Issue by selenehyun** [gorgeous30/Shoppingmall#3]
https://github.com/gorgeous30/1week_homework/blob/b97cc9e05185b8673f30401d4f410c728463467a/1week_homework.html#L36

https://github.com/gorgeous30/1week_homework/blob/b97cc9e05185b8673f30401d4f410c728463467a/1week_homework.html#L55

id가 겹치고있어요!
이러면 안되는 이유는, 브라우저는 한 페이지에 아이디가 1개만 존재한다고 믿기 때문이에요. 약속이라서!

**Comment by gorgeous30** [comment]
> https://github.com/gorgeous30/1week_homework/blob/b97cc9e05185b8673f30401d4f410c728463467a/1week_homework.html#L36
> 
> https://github.com/gorgeous30/1week_homework/blob/b97cc9e05185b8673f30401d4f410c728463467a/1week_homework.html#L55
> 
> id가 겹치고있어요!
> 이러면 안되는 이유는, 브라우저는 한 페이지에 아이디가 1개만 존재한다고 믿기 때문이에요. 약속이라서!

질문 1. inputGroup-sizing-default이라는 아이디가 '주문자 이름'과 '주소' input-group-text class에 동일하게 적용되고 있는데, 그럼 이 둘도 각자 다른 id를 주어야 하는건가요?
질문 2. aria-describedby는 aria를 설명하는 짤막한 descriptive id라고 보면 되나요? id라고 명확하게 명시되어 있는 것은 아니지만 동일한 역할을 하기 때문에 동일한 네이밍을 주면 안되는 것인지 궁금합니다.

**Comment by selenehyun** [comment]
@gorgeous30 제가 코드 인용을 잘못했네요 😞

1. id가 겹친 부분은 
https://github.com/gorgeous30/1week_homework/blob/b97cc9e05185b8673f30401d4f410c728463467a/1week_homework.html#L36
https://github.com/gorgeous30/1week_homework/blob/b97cc9e05185b8673f30401d4f410c728463467a/1week_homework.html#L53
이 두 span 부분이었습니다 ㅎㅎ
id라는 attribute는 같은 값으로 존재 하면 안되니 두개를 다른 값으로 주어야 해요!
2. `aria-describedby`는 "웹 접근성" 이라는걸 위해 존재하는 아이인데, 여기서는 일단 span에 작성한 id 값을 그대로 주면 됩니다 :)
그러나 지금 우리에게 당장은 필요 없으니 지우셔도 문제가 발생하지는 않아요!

**Comment by gorgeous30** [comment]
4/13 수정완료
